import { Injectable, Inject, Scope } from '@nestjs/common';
import { REQUEST } from '@nestjs/core';
import type { Request } from 'express';

/**
 * Example of how to propagate the request ID in outgoing calls using Axios.
 * NOTE: To use this, you must set the scope of your service to Scope.REQUEST
 * so that the REQUEST object can be injected.
 *
 * Example usage:
 *
 * @Injectable({ scope: Scope.REQUEST })
 * export class MyExternalApiService {
 *   constructor(
 *     @Inject(REQUEST) private request: Request,
 *     private httpService: HttpService
 *   ) {
 *     this.httpService.axiosRef.interceptors.request.use((config) => {
 *       const reqId = this.request.id; // Generated by pino-http
 *       if (reqId) {
 *         config.headers['x-request-id'] = reqId;
 *       }
 *       return config;
 *     });
 *   }
 * }
 */
@Injectable({ scope: Scope.REQUEST })
export class OutgoingHttpInterceptorExample {
  constructor(@Inject(REQUEST) private readonly request: Request) {}

  public getHeadersWithRequestId(): Record<string, string> {
    const headers: Record<string, string> = {};
    if (this.request?.id) {
      headers['x-request-id'] = String(this.request.id);
    }
    return headers;
  }
}
